services:
  - type: web
    name: autumn-park
    runtime: docker
    plan: free
    healthCheckPath: /park
    envVars:
      - key: BOOTSTRAP_CODE
        value: ${BOOTSTRAP_CODE}
      - key: TURSO_DATABASE_URL
        value: ${TURSO_DATABASE_URL}
      - key: TURSO_AUTH_TOKEN
        value: ${TURSO_AUTH_TOKEN}
      - key: UPLOAD_DIR
        value: /app/uploads
